# Generated by Django 5.1.6 on 2025-03-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myauth',
            old_name='name',
            new_name='username',
        ),
    ]
