# Generated by Django 5.1.6 on 2025-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
